import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
// import '../styles/animation.scss'
import { Toaster } from '@/components/ui/toaster'
import AuthProvider from './__context__/AuthContext'
import { QueryProvider } from '@/lib/react-query/QueryProvider'
// import Bottombar from '@/components/shared/Bottombar'
import ShowNavigation from '@/components/shared/ShowNavigation'
// import RightSidebar from '@/components/shared/RightSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <head>
        <title>Infi-gram</title>
      </head>
      <body className={`${inter.className} bg-[#000] w-full text-white win-custom-scrollbar bg_img select-none bg-100`}>
        <QueryProvider>
          <AuthProvider>
            <div className="w-full h-full min-h-screen md:flex max-md:flex max-md:flex-col max-md:items-center">
              <ShowNavigation />
              <section className="flex flex-1 min-w-[270px] h-full min-h-screen w-full items-center justify-center max-[967px]:my-10 mx-auto min-[967px]:max-[1215px]:ml-60">
                {children}
              </section>
              {/* <RightSidebar /> */}
              
            </div>
          </AuthProvider>
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  )
}
